### ISSUE TITLE
Is it possible to replace underscores ("_") with spaces (" ") in HELP-Commands.txt?

### ISSUE THREAD

**Issue by Avastgard** [kalekje/LNCHR-pub#10]
Commands like `a dir` are the hardest for me to remember, and if I type `a ` on the GUI, the tooltip does not show them because in `HELP-Commands.txt` they are stored as `a_dir`. I can type `a_` on the GUI to preview them, but that's inconvenient and feels clunky. Would it be possible for `HELP-Commands.txt` to store spaces as spaces instead of underscores?

**Comment by kalekje** [comment]
I actually addressed this in the newest version.. please double check. The help file provided in the updated codebase doesn't have underscores so the macro very likely is the newest version.

**Comment by Avastgard** [comment]
Hm, I see. I kept my old `LNCHR-CommandsGenerator.xlsm` spreadsheet so I wouldn't loose all the custom commands I had added. Is there an easy way to address this or do I have to always copy my commands and paste on the most recent spreadsheet? I changed a lot of your default ones that would be reverted if I used your sheet.

**Comment by kalekje** [comment]
You could either change the macro or copy and paste. The major difference in the new one is the extra column which has the optional boolean flag.

**Comment by Avastgard** [comment]
I ended up just copying and pasting my commands on the new spreadsheet. All I had to do besides that was accomodate the new column.

I missed the boolean flag update because I was still using the previous version of my spreadsheet. Nice! This will surely make my life a lot easier.

Here is a list of Windows Run Commands I had added to my sheet that I think you could include in yours by default:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/flima/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/flima/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#FFD965" vlink="#FEE599">


Settings page | Uri / Setting Name | Category
-- | -- | --
Edge web browser | microsoft-edge:url | Apps
Home page for Settings | ms-settings: | Windows
About (device name/specification) | ms-settings:about | Windows
Activation | ms-settings:activation | Security
Apps & features | ms-settings:appsfeatures | Apps
Apps for websites | ms-settings:appsforwebsites | Apps
App volume and device preferences (1903) | ms-settings:apps-volume | Audio
Set up a kiosk | ms-settings:assignedaccess | Security
AutoPlay | ms-settings:autoplay | Apps
Backup | ms-settings:backup | Storage
Battery Saver | ms-settings:batterysaver | Power
Battery Saver - settings | ms-settings:batterysaver-settings | Power
Battery Saver - usage | ms-settings:batterysaver-usagedetails | Power
Bluetooth & Connected Devices | ms-settings:bluetooth | Network
Clipboard | ms-settings:clipboard | Apps
Connect to a wireless display | ms-settings-connectabledevices:devicediscovery | Display
Bluetooth & Connected Devices | ms-settings:connecteddevices | Network
Cortana | ms-settings:cortana | Search
Cortana permissions | ms-settings:cortana-permissions | Search
Cortana more details | ms-settings:cortana-moredetails | Search
Windows Search | ms-settings:cortana-windowssearch | Search
Shared experiences | ms-settings:crossdevice | Network
Data Sense | ms-settings:datausage | Storage
Date & Time | ms-settings:dateandtime | Region & Language
Default apps | ms-settings:defaultapps | Apps
Delivery Optimization | ms-settings:delivery-optimization | Windows
For developers | ms-settings:developers | Apps
Device Encryption (where available) | ms-settings:deviceencryption | Security
Touchpad | ms-settings:devices-touchpad | Devices
Display | ms-settings:display | Display
Graphics Advanced scaling settings | ms-settings:display-advanced | Display
Graphics performance preference | ms-settings:display-advancedgraphics | Display
Ease of Access Audio (build 17035+) | ms-settings:easeofaccess-audio | Accessibility
Closed Captioning | ms-settings:easeofaccess-closedcaptioning | Accessibility
Color Filters (build 17025+) | ms-settings:easeofaccess-colorfilter | Accessibility
Adaptive Color Filters Link | ms-settings:easeofaccess-colorfilter-adaptivecolorlink | Accessibility
Text Cursor | ms-settings:easeofaccess-cursor | Accessibility
Mouse Pointer (Cursor & pointer,   build 17040+) | ms-settings:easeofaccess-cursorandpointersize | Accessibility
Display Text scaling (build 17025+) | ms-settings:easeofaccess-display | Accessibility
Eye Control (build 17035+) | ms-settings:easeofaccess-eyecontrol | Accessibility
High Contrast | ms-settings:easeofaccess-highcontrast | Accessibility
Keyboard | ms-settings:easeofaccess-keyboard | Devices
Magnifier | ms-settings:easeofaccess-magnifier | Accessibility
Mouse | ms-settings:easeofaccess-mouse | Accessibility
Mouse Pointer (Cursor & pointer,   build 17040+) | ms-settings:easeofaccess-mousepointer | Accessibility
Narrator | ms-settings:easeofaccess-narrator | Audio
Start Narrator after sign-in | ms-settings:easeofaccess-narrator-isautostartenabled | Audio
Other options | ms-settings:easeofaccess-otheroptions | Accessibility
Speech recognition (build 17035+) | ms-settings:easeofaccess-speechrecognition | Accessibility
Email & app accounts | ms-settings:emailandaccounts | Security
Family & other users | ms-settings:family-group | Security
Find My Device | ms-settings:findmydevice | Security
Fonts (build 17083+) | ms-settings:fonts | Customisation
Lock screen | ms-settings:lockscreen | Security
Offline Maps | ms-settings:maps | Apps
Download maps | ms-settings:maps-downloadmaps | Apps
Mouse & Touchpad Devices | ms-settings:mousetouchpad | Devices
Multitasking | ms-settings:multitasking | Display
Network & Internet | ms-settings:network | Network
Airplane mode (wireless/bluetooth) | ms-settings:network-airplanemode | Network
Cellular Network | ms-settings:network-cellular | Network
Dial-up Network | ms-settings:network-dialup | Network
DirectAccess | ms-settings:network-directaccess | Network
Ethernet Network | ms-settings:network-ethernet | Network
Mobile Hotspot | ms-settings:network-mobilehotspot | Network
Proxy (Network) | ms-settings:network-proxy | Network
Network Status | ms-settings:network-status | Network
VPN | ms-settings:network-vpn | Network
Wi-Fi | ms-settings:network-wifi | Network
Manage known Wi-Fi | ms-settings:network-wifisettings | Network
Night light settings | ms-settings:nightlight | Customisation
Notifications and Actions | ms-settings:notifications | Customisation
Optional features | ms-settings:optionalfeatures | Apps
Family & other users | ms-settings:otherusers | Security
Personalization | ms-settings:personalization | Customisation
Backgrounds | ms-settings:personalization-background | Customisation
Colors | ms-settings:personalization-colors | Customisation
Colors | ms-settings:colors | Customisation 
Start Menu | ms-settings:personalization-start | Customisation
Start Menu (choose which folders appear) | ms-settings:personalization-start-places | Customisation
Power & Sleep | ms-settings:powersleep | Power
Printers | ms-settings:printers | Devices
Privacy | ms-settings:privacy | Privacy
Account info (share between apps) | ms-settings:privacy-accountinfo | Privacy
Activity history (build 17040+) | ms-settings:privacy-activityhistory | Privacy
App diagnostics (share between apps) | ms-settings:privacy-appdiagnostics | Privacy
Automatic online file downloads | ms-settings:privacy-automaticfiledownloads | Apps
Background apps | ms-settings:privacy-backgroundapps | Apps
File System (share between apps) | ms-settings:privacy-broadfilesystemaccess | Privacy
Calendar (share between apps) | ms-settings:privacy-calendar | Privacy
Call history (share between apps) | ms-settings:privacy-callhistory | Privacy
Contacts (share between apps) | ms-settings:privacy-contacts | Privacy
Unpaired devices (share between apps) | ms-settings:privacy-customdevices | Privacy
Document Library (share between apps) | ms-settings:privacy-documents | Privacy
Email (share between apps) | ms-settings:privacy-email | Privacy
Eye tracker (requires eyetracker   hardware) | ms-settings:privacy-eyetracker | Privacy
Feedback & diagnostics (privacy) | ms-settings:privacy-feedback | Security
Send Diagnostic Data to Microsoft | ms-settings:privacy-feedback-telemetryviewergroup | Privacy
Location (share between apps) | ms-settings:privacy-location | Privacy
Messaging (share between apps) | ms-settings:privacy-messaging | Privacy
Microphone (share between apps) | ms-settings:privacy-microphone | Privacy
Motion (share between apps) | ms-settings:privacy-motion | Privacy
Notifications (share between apps) | ms-settings:privacy-notifications | Privacy
Picture Library (share between apps) | ms-settings:privacy-pictures | Privacy
Radio (share between apps) | ms-settings:privacy-radios | Privacy
Online Speech recognition | ms-settings:privacy-speech | Privacy
Remember typing patterns | ms-settings:privacy-speechtyping | Privacy
Tasks (share between apps) | ms-settings:privacy-tasks | Privacy
Video Library (share between apps) | ms-settings:privacy-videos | Privacy
Voice activation (apps can listen) | ms-settings:privacy-voiceactivation | Privacy
Webcam (share between apps) | ms-settings:privacy-webcam | Privacy
Projecting to this PC | ms-settings:project | Display
Airplane mode (wireless/bluetooth) | ms-settings:proximity | Network
Focus assist (build 17074+) | ms-settings:quiethours | Apps
Focus assist (build 17074+) | ms-settings:quietmomentshome | Apps
Recovery - Reset/Advanced startup | ms-settings:recovery | Windows
Region | ms-settings:regionformatting | Region & Language
Region & language | ms-settings:regionlanguage | Region & Language
Remote Desktop | ms-settings:remotedesktop | Network
Default Save Locations | ms-settings:savelocations | Storage
Display Screen rotation | ms-settings:screenrotation | Display
Search details | ms-settings:search-moredetails | Search
Search Permissions & search history | ms-settings:search-permissions | Search
Sign-in options | ms-settings:signinoptions | Security
Dynamic Lock | ms-settings:signinoptions-dynamiclock | Security
Windows Hello face setup | ms-settings:signinoptions-launchfaceenrollment | Security
Windows Hello fingerprint setup | ms-settings:signinoptions-launchfingerprintenrollment | Security
Security Key setup | ms-settings:signinoptions-launchsecuritykeyenrollment | Security
Sound (build 17063+) | ms-settings:sound | Audio
Manage sound devices (disable/test) | ms-settings:sound-devices | Audio
Speech | ms-settings:speech | Audio
Startup (build 17017+) | ms-settings:startupapps | Customisation
Storage Sense configuration | ms-settings:storagepolicies | Storage
Storage Sense | ms-settings:storagesense | Storage
Sync your settings | ms-settings:sync | Network
Tablet mode | ms-settings:tabletmode | Customisation
Taskbar | ms-settings:taskbar | Apps
Themes | ms-settings:themes | Customisation
Troubleshoot - Fix Windows Update | ms-settings:troubleshoot | Windows
Typing | ms-settings:typing | Accessibility
USB | ms-settings:usb | Devices
Video playback (build 16215+) | ms-settings:videoplayback | Display
Windows Security (Defender) | ms-settings:windowsdefender | Security
Windows Insider Program (beta's) | ms-settings:windowsinsider | Windows
Windows Update | ms-settings:windowsupdate | Security
WinUpdate - Check for updates | ms-settings:windowsupdate-action | Security
WinUpdate - Active Hours | ms-settings:windowsupdate-activehours | Security
WinUpdate - Update history | ms-settings:windowsupdate-history | Security
WinUpdate - Optional updates | ms-settings:windowsupdate-optionalupdates | Security
WinUpdate - Advanced options | ms-settings:windowsupdate-options | Security
WinUpdate - Restart options | ms-settings:windowsupdate-restartoptions | Security
Access work or school | ms-settings:workplace | Network
Your info (Microsoft account) | ms-settings:yourinfo | Security
Software Center (SCCM) | softwarecenter: | Apps
Windows Security at a glance | windowsdefender: | Security



</body>

</html>

**Comment by kalekje** [comment]
Thanks for sharing. I wuld consider adding those to a query and leverage the autocomplete. Something to note though, I can find most of these by pressing the win/start key and typing.
