### ISSUE TITLE
README/documentation: reference original author

### ISSUE THREAD

**Issue by Gewerd-Strauss** [kalekje/LNCHR-pub#16]
Hello,

I have recently stumbled over this script, which is noted to be inspired by https://github.com/TheBestPessimist/AutoHotKey-Launcher.
It is not much, but I think it should be noted that that is again only a fork of https://github.com/plul/Public-AutoHotKey-Scripts.
Ironically, I just stumbled upon this in the ahk-boards by chance.

I note this merely for the sake of completeness, and because I think that the original work should at least be mentioned (even if it is not the version you forked yourself). If you think this is unreasonable, please disregard this issue.

I have my own branch of plul's code, and am considering moving over to v2 by adopting this repo instead, as it is significantly easier to maintain for most my needs - and it is time to weed out old things anyways.

There are a variety of things I want to implement and am happy to open PRs for once done which I would consider significant improvements, but those will be done slowly - as I have quite a bit of stuff to do currently.

Thank you.  
Sincerely,  
~Gw

**Comment by kalekje** [comment]
Thanks for the input--will revise on the next update.
