### ISSUE TITLE
Quick question about the source code

### ISSUE THREAD

**Issue by pa-0** [kalekje/LNCHR-pub#17]
I'm a novice and trying to get into AutoHotkey. I feel like this tool would be the perfect way to get my foot in the door, just because I really like it, and even more so would like to "make it my own" by customizing it, adding features, etc.

I am exploring the source code just for the sake of familiarizing myself with it and getting a grasp on the structure.  I noticed this file is formatted differently than the rest:
![image](https://github.com/user-attachments/assets/4d126718-3dc7-4296-8cbb-7f1eb529870d)

It looks like the majority of the code in this file resides on one line. Is there a particular benefit/purpose to structuring it this way? Maybe to be parsed later?

**Comment by kalekje** [comment]
Hey thanks for taking an interest! If you read the documentation, it says that I use an Excel Macro to manage my code for this portion. There is no advantage to writing everything on one line.

**Comment by pa-0** [comment]
I did read that - I just didn't make the connection. Thanks!
