### ISSUE TITLE
Macro command character limit

### ISSUE THREAD

**Issue by Avastgard** [kalekje/LNCHR-pub#5]
I have noticed there is a command character limit in the macro: if the command has more than 6 characters, pressing Ctrl+L will show a Runtime Error '5' message. Clicking debug will show this:

![2023_11_14 @ 14_46_08 (1026x541)](https://github.com/kalekje/LNCHR-pub/assets/20537747/6719949c-419f-4e0b-a498-5ca1b49fb5e3)

I can still manually edit `LNCHR-Commands.ahk` and input a command with more than 6 characters, but that kind of defeats the purpose of using the spreadsheet.

Is there a way to bypass this limitation or at least increase the command character limit the macro will accept?

**Comment by Avastgard** [comment]
Nevermind, I managed to edit the command string's length by editing the macro on line 39 (`16` is the new character limit):

`helpStr = helpStr & PadRight(Replace(cmd, " ", "_"), 16, " ") & ": " & desc & vbCr`

**Comment by kalekje** [comment]
Bingo. That is for the help file (command `?`). The 6 just codes the spacing between the command and semi colon.

By the way, after I'm done my thesis I should have a nice update: memory for all query type functions (not just calculator, I have this working already), and then I'm hoping to add auto-complete.

I'll also allow for a mapping between categories and boolean flags (eg. like `_work`) as you mentioned in your other thread.

**Comment by Avastgard** [comment]
Excellent, I'm looking forward to those updates!

Good luck with your thesis!
