### ISSUE TITLE
Spreadsheet commands with special characters result in errors

### ISSUE THREAD

**Issue by Avastgard** [kalekje/LNCHR-pub#6]
If I have a command with a special character in the spreadsheet, pressing Ctrl + L will generate a script with incorrect character.

For example, the command `revisão` will produce this line of code:

```
if ((input == "revis㯢) and (UsingAnyWorkcomputer)) ;  
{
close_lngui()

return
}
```
![2023_11_16 @ 14_44_55 (523x166)](https://github.com/kalekje/LNCHR-pub/assets/20537747/22e65c5a-d03c-453e-a237-2d071928eb60)

**Comment by kalekje** [comment]
Does the code work or no? I think this depends on the type of encoding you view your code in.

I tried:
![image](https://github.com/kalekje/LNCHR-pub/assets/51413662/1a48b72c-e1b3-46a8-873f-4edae071507b)
Which generates the following when viewed on notepad++ with ANSI encoding:
![image](https://github.com/kalekje/LNCHR-pub/assets/51413662/d09fcb4d-5fd0-48b9-9c70-76b2bbce0879)
But switching to UTF-8:
![image](https://github.com/kalekje/LNCHR-pub/assets/51413662/e2d0539b-a19f-4252-a3c0-7e35dcdc584b)

**Comment by kalekje** [comment]
Maybe something like this will help: https://www.mrexcel.com/board/threads/vba-create-text-file-in-utf-8-rather-then-ansi.1204545/

**Comment by Avastgard** [comment]
> Does the code work or no?

It doesn't. Sometimes it throws me an error message and prevents me from reloading the script. Other times, the script reloads, but the command fails every time. These behavior seem to be related to the kind of special character I use.


> I think this depends on the type of encoding you view your code in.
> 
> I tried: ![image](https://user-images.githubusercontent.com/51413662/283548789-1a48b72c-e1b3-46a8-873f-4edae071507b.png) Which generates the following when viewed on notepad++ with ANSI encoding: ![image](https://user-images.githubusercontent.com/51413662/283548891-d09fcb4d-5fd0-48b9-9c70-76b2bbce0879.png) But switching to UTF-8: ![image](https://user-images.githubusercontent.com/51413662/283548952-e2d0539b-a19f-4252-a3c0-7e35dcdc584b.png)

Yes, opening the code with notepad shows me the correct characters, but on Scite4AutoHotkey, it shows the weird character I posted in the OP.

How should I approach this? I'm thinking that since the macro recreates the script everytime it runs, then the issue should be in the way the macro always creates the file with ANSI encoding, no? I tried changing the encoding of LNCHR-Main.ahk to UTF-8 and UTF-8 without BOM, but everytime I ran the macro, the encoding defaulted back to ANSI.

Your suggestion from your second post might help, but it's a little too advanced for me. Might give it a shot some time in the future, though.

**Comment by kalekje** [comment]
Try changing the Flase to True in the VBA file as shown below, it seems to work for me:

![image](https://github.com/kalekje/LNCHR-pub/assets/51413662/5d871772-b54c-48c3-9254-28eaa43ebcba)


From here: https://stackoverflow.com/a/10101320/11551386

**Comment by Avastgard** [comment]
Sweet, it worked and was far easier than I thought! 

Sorry for opening so many issues, but I'm in the process of adopting your code as my daily driver and so many questions have been appearing so far. Thanks for your support!
