### ISSUE TITLE
Is it possible to use Search without using REPLACEME?

### ISSUE THREAD

**Issue by Avastgard** [kalekje/LNCHR-pub#7]
As far as I know, the search functionality only works by typing the exact same text you want REPLACEME to susbtitute. So, if I want to go to the r/AutoHotkey subreddit, I'd need to type `/`, then `AutoHotkey`.

Would it be possible to alter this behavior so the second query (`AutoHotkey`) triggers an autonomous action instead of replacing part of the command? For example, I would type `/`, then, `ahk`, and it would go to the r/AutoHotkey subreddit (i.e., without having to type `AutoHotkey`).

**Comment by kalekje** [comment]
Yup. The "search" type on the Excel Macrois just a shortcut to enable a query with a function with replacement text you specify, for example:

```
if input == "/" ; r/ 
{
lngui_enable_query("r/", make_run_ReplaceTexts_func("https://www.reddit.com/r/REPLACEME"))
return
}
```

The `make_run_ReplaceTexts_func` returns a function. You can write whatever function you want (and include a built-in lookup table for shortcuts like you're proposing, for example.)

Remember that the "types" on the Excel macro only serve as shortcuts. You can specify no type or "n" type and write whatever code you want. For example, the Outlook search function uses the "n" type (does whatever code you want without closing the GUI, this is what you would want)

In the macro, the code is generated. 

```
lngui_enable_query("Outlook", OutlookSearch)
```

Look at `LNCHR-Funcs.ahk`

we have

```
OutlookSearch(searchstr)
{
    searchstr := StrReplace(searchstr, "!", " hasattachments:yes")
    olApp := GetOutlookCom()
    static olSearchScopeAllFolders := 2
    olApp.ActiveExplorer.Search(searchstr, olSearchScopeAllFolders) ; Activate the Outlook window
    WinActivate("ahk_class rctrl_renwnd32") ; Send Tab to hide the "suggested searches" drop down
    ControlSend "{Tab}", "RICHEDIT60W1", "ahk_class rctrl_renwnd32"
    return
}

```

searchstr is whatever you enter in the GUI after query is enabled.


So you could do something like this by switching to "n" type in your Excel book.
`lngui_enable_query("go to reddit", gotosubreddit)`

and make this function:



```
gotosubreddit(replacement){
    runstring :="https://www.reddit.com/r/REPLACEME"
    if replacement == "ahk" { replacement := "autohotkey"}
    runString := StrReplace(runstring, "REPLACEME", replacement)
    tryrun(runstring)
}
```

Not tested...

**Comment by Avastgard** [comment]
Thank you for the detailed explanation and sorry it took me so long to answer this. I only got to test it now.

I'm still a noob with functions, so please bear with me. 

My main use case for this is to able to use the LNCHR gui to go directly to a specific Microsoft Teams chat. Type "t " > type name of person > open Teams chat with that person.

Here's what I did so far:

1. Added this line to the Excel spreadsheet: Command: `t ` (notice there is a space after "t"); Type: `n`; Field 1: `lngui_enable_query("Chat with", teamschat)`.
2. This generated the following lines on `LNCHR-Commands.ahk`:
```
if ((input == "t ") and (UsingWorkcomputer)) ; t  
{
lngui_enable_query("Chat with", teamschat)
return
}
```
3. On `LNCHR-Funcs.ahk`, I added this function:
```
teamschat(replacement){
    runString :="https://teams.microsoft.com/l/chat/0/0?users=REPLACEME" ; I have tested this url to work perfectly if REPLACEME is the e-mail of the person I want to chat with
    if replacement == "joe" ( replacement := "joe.smith@domain.com") ; I would probably need to make a list of names to type and e-mails to replace it, but I have no idea how to do it
    runString := StrReplace(runString, "REPLACEME", replacement)
    tryrun(runString)
}
```
The behavior I expected is to open LNCHR gui, type `t `, then the name of the person I want to chat with, and it would open the Teams chat. **What it actually does is open a new Teams chat**, not with the person I specified. This leads me to believe REPLACEME is not working as it should, for some reason. 

Do you have any idea on how I can solve this problem?

**Comment by kalekje** [comment]
First of all, cool idea! I might have to borrow it ;)

I would recommend using `MsgBox(runString)` before `tryrun` and see what the actual command is that is attempted to be run. It seems like REPLACEME is indeed not being replaced. If you see it being left there in the message box I would then print out add `MsgBox(replacement)` as the first line and before tryrun.

I don't see why your code shouldn't work. As a general tip, I recommend ensure replacement is stripped of spaces and lower cased before comparing to `"joe"`

For using names/emails, I would use an AHK Map object--it's useful to learn. 

I forget which version is currently active, but memory should work for this automatically which will be handy.

**Comment by Avastgard** [comment]
Sorry for the late reply again.

I tested this as you suggested and the all the results suggested the code was correct. Yet, it still produced the same results.

I ended up creating individual entries for every person I usually chat with on Teams, and this seems to be more practical. The only issue I found was activating group chats, but that's unrelated to LNCHR.

Thanks for the help!
