### ISSUE TITLE
tray icon not showing

### ISSUE THREAD

**Issue by micjoh** [kalekje/LNCHR-pub#8]
Tray icon (menu) is not showing in latest version.
Previous version did show the tray icon.

**Comment by kalekje** [comment]
Interesting.. I tried moving the TrayIcon call around, changing the GUI settings, following this guide: https://www.autohotkey.com/boards/viewtopic.php?t=66010, but all to no avail. Will look into it a bit more and see.

**Comment by micjoh** [comment]
I commented out :
#Include QuickTips.ah2  in LNCHR-main
and row 15 **QuickTrayTip("failed to run:`n" s, tit:="LNCHR")** 

Tray icon is back - the quick help tool tip is working but not looking so nice (no themed)

**Comment by kalekje** [comment]
Ahh found it. Comment out line 2 in that file instead!  Thanks, will update soon.

**Comment by micjoh** [comment]
Yeah found it too 
comment out #notrayicon :-)

works great now

**Comment by kalekje** [comment]
Done
