### ISSUE TITLE
Is it possible to change position of the quick reference tooltip?

### ISSUE THREAD

**Issue by Avastgard** [kalekje/LNCHR-pub#9]
I'd like to have the quick reference tooltip under the GUI, similar to what PowerToys does. Is this possible? What would I have to change?

**Comment by kalekje** [comment]
Yup, see the `lngui_show_command_tips()` function and change the arguments to the `ToolTip` call. I believe by default I have it set 500 pixels off to the right of the gui.

**Comment by Avastgard** [comment]
Sweet, thanks!
I placed it right under the GUI. Is it possible to set transparency like in the GUI?

**Comment by kalekje** [comment]
I adopted that from https://www.autohotkey.com/boards/viewtopic.php?f=83&t=113308 (see `QuickTips.ahk`, I do not believe transparency can be set. You might be able to use a more sophisticated ToolTip library, there are plenty out there.
